services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest_app
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: nestuser
      DB_PASSWORD: nestpassword
      DB_DATABASE: nestdb
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
